_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.0
            "6": 4.47.0
            "8":
                - 5
            "12": 0.19.0
            "13": linux-x86_64
dataloader_num_workers:
    value: 60
eval_batch_size:
    value: 2
gradient_accumulation_steps:
    value: 1
local_rank:
    value: -1
logging_dir:
    value: ./logs
logging_steps:
    value: 100
max_length:
    value: 512
model_name_or_path:
    value: /mnt/file2/changye/model/fine_tuned_t5/fine_tuned_t5
num_epochs:
    value: 3
output_dir:
    value: /mnt/file2/changye/model/t5-formal-finetuned
train_batch_size:
    value: 2
train_file:
    value: /mnt/file2/changye/dataset/casual_formal_pair_ACL40k/train
val_file:
    value: /mnt/file2/changye/dataset/casual_formal_pair_ACL40k/val
wandb_project:
    value: academic_finetuning
