_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.0
            "6": 4.47.0
            "8":
                - 5
            "12": 0.19.0
            "13": linux-x86_64
