deepspeed --num_gpus=8 train.py \
    --train_dataset /mnt/file2/changye/dataset/NLP/casual_formal_pair_ACL40k/train \
    --val_dataset /mnt/file2/changye/dataset/NLP/casual_formal_pair_ACL40k/val \
    --model_path /mnt/file2/changye/model/Mistral-7B-Instruct-v0.2 \
    --epochs 3 \
    --batch_size 4 \
    --learning_rate 5e-5 \
    --fp16 \
    --deepspeed_config ds_config.json \
    --wandb_project Mistral \
    --wandb_run_name Mistral \
    --output_dir /mnt/file2/changye/model/NLP/Mistral-7B-Instruct-v0.2-finetune 
